<?php
/**
 * This file is part of Onion
 *
 * Copyright (c) 2014-2016, Humberto Lourenço <betto@m3uzz.com>.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *   * Redistributions of source code must retain the above copyright
 *     notice, this list of conditions and the following disclaimer.
 *
 *   * Redistributions in binary form must reproduce the above copyright
 *     notice, this list of conditions and the following disclaimer in
 *     the documentation and/or other materials provided with the
 *     distribution.
 *
 *   * Neither the name of Humberto Lourenço nor the names of his
 *     contributors may be used to endorse or promote products derived
 *     from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * @category   PHP
 * @package    Onion
 * @author     Humberto Lourenço <betto@m3uzz.com>
 * @copyright  2014-2016 Humberto Lourenço <betto@m3uzz.com>
 * @license    http://www.opensource.org/licenses/BSD-3-Clause  The BSD 3-Clause License
 * @link       http://github.com/m3uzz/onionfw
 */
 
use Onion\Lib\String;
use Onion\Log\Debug;

$this->headTitle($lsTitle);

function print_value ($pmValue, $psLabel = null)
{
	if (is_array($pmValue))
	{
		echo "<ul>";
		
		foreach ($pmValue as $lsLabel => $lmValue)
		{
			echo "<li>" . ucfirst($lsLabel) . ": ";
			
			print_value ($lmValue, $lsLabel);
			
			echo "</li>";
		}
		
		echo "</ul>";
	}
	else
	{
		echo "<code>" . strip_tags($pmValue) . "</code>";
	}
}

?>
<div class="panel panel-default">
	<div class="panel-heading">
		<div class="row">
			<div class="col-md-12">
				<h4><?php echo $lsTitle; ?></h4>
			</div>
		</div>
	</div>
	<div class="panel-body">
		<h4>Data: <span class="badge"><?php echo String::getDateTimeFormat($laData['dtInsert']); ?></span></h4>
		<h4>User: <span class="badge">[<?php echo $laData['User_id']; ?>] <?php echo $laData['UserName']; ?></span></h4>
		<h4>Group: <span class="badge"><?php echo $laData['UserGroup']; ?></span></h4>
		<h4>IP: <span class="badge"><?php echo $laData['stIP']; ?></span></h4>

		<br/>
		
		<fieldset>
			<legend>Log:</legend>
			<?php 
			$laMsg = json_decode($laData['stMsg'], true);
			
			if (is_array($laMsg))
			{
				print_value ($laMsg);
			}
			else 
			{
				echo "<code>" . $laData['stMsg'] . "</code>"; 
			}
			?>
		</fieldset>
	
		<br/>
		
		<fieldset>
			<legend>Server:</legend>
			<?php 
			$laServer = json_decode($laData['txtServer'], true);
			
			print_value ($laServer);
			?>
		</fieldset>
	</div>
	<div class="panel-footer">
		<a href="/<?php echo $lsRoute; ?>">Voltar</a>
	</div>
</div>	