<?php
/**
 * This file is part of Onion
 *
 * Copyright (c) 2014-2016, Humberto Lourenço <betto@m3uzz.com>.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *   * Redistributions of source code must retain the above copyright
 *     notice, this list of conditions and the following disclaimer.
 *
 *   * Redistributions in binary form must reproduce the above copyright
 *     notice, this list of conditions and the following disclaimer in
 *     the documentation and/or other materials provided with the
 *     distribution.
 *
 *   * Neither the name of Humberto Lourenço nor the names of his
 *     contributors may be used to endorse or promote products derived
 *     from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * @category   PHP
 * @package    Onion
 * @author     Humberto Lourenço <betto@m3uzz.com>
 * @copyright  2014-2016 Humberto Lourenço <betto@m3uzz.com>
 * @license    http://www.opensource.org/licenses/BSD-3-Clause  The BSD 3-Clause License
 * @link       http://github.com/m3uzz/onionfw
 */
 
$this->headTitle('Change Phone Extension ' . strtolower($lsTitleS));

$loForm->setAttribute('data-act', $this->url($lsRoute, array(
	'action' => 'change-phone-extension'
)));

$loForm->setAttribute('action', '#');
$loForm->setAttribute('data-request', 'AJAX');
$loForm->setAttribute('data-container', '#ChangePhoneExtensionContainer');

$loForm->prepare();

$lsForm = '
			<div id="ChangePhoneExtensionContainer" >
				<div class="row">';

$lsForm .= $this->headLink()->appendStylesheet($this->basePath('/vendor/onion/css/form.css'));

$lsForm .= $loForm->getFlashMessage($this);

$lsForm .= $this->form()->openTag($loForm);

$lsForm .= '
					<input type="hidden" name="back" value="' . $lsBack . '">
					<input type="hidden" name="w" value="' . $loForm->getWindowType() . '">';

$lsForm .= $loForm->renderFieldSet($this);

$lsForm .= $this->form()->closeTag();

$lsForm .= $this->inlineScript()->prependFile($this->basePath('/vendor/onion/js/form.js'));

$lsForm .= '
				</div>
			</div>';

echo $lsForm;